// Generated by https://quicktype.io

import { Cliente } from "./cliente.interface";
import { Usuario } from "./usuario.interface";

export interface Cotizacion {
  idCotizacion:        number;
  idCliente:           number;
  idUsuario:           number;
  nombre:              string;
  editadoPor:          null;
  descaripcion:        null;
  estado:              number;
  total:               string;
  createdAt:           string;
  updatedAt:           null;
  numeroDocumento:     null;
  detalleCotizacions:  any[];
  idClienteNavigation: Cliente;
  idUsuarioNavigation: Usuario;
}



