// Generated by https://quicktype.io

import { Cliente } from "./cliente.interface";
import { DetalleCotizacion } from "./detalleCotizacion.interface";
import { Usuario } from "./usuario.interface";

export interface Cotizacion {
  idCotizacion:        number;
  idCliente:           number;
  idUsuario:           number;
  nombre:              string;
  editadoPor:          Date | null;
  nombreCliente:       string;
  emailCliente:        string;
  vendedor:            string;
  descripcion:         string;
  estado:              number;
  valorIva:            number;
  total:               number;
  createdAt:           Date ;
  updatedAt:           Date ;
  expiracion:          Date;
  comentarios:         string;
  numeroDocumento:     number;
  detalleCotizacions:  DetalleCotizacion[];
  idClienteNavigation: Cliente;
  idUsuarioNavigation: Usuario;
}



export interface CotizacionDTO {
  idCotizacion:        number;
  idCliente:           number;
  idUsuario:           number;
  nombre:              string;
  estado:              number;
  expiracion:          Date;
  total:               number;
  descripcion:         string;
  comentarios:         string;
  detalleCotizacions:  DetalleCotizacion[];
}
